version: '3.3'
services:
  zookeeper:
    container_name: zookeeper-dse
    image: debezium/zookeeper:1.6
    ports:
      - "0.0.0.0:2191:2181"
      - "0.0.0.0:2898:2888"
      - "0.0.0.0:3898:3888"
  kafka:
    container_name: kafka-dse
    image: debezium/kafka:1.6
    ports:
      - "0.0.0.0:9102:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
  cassandra-dse:
    container_name: cassandra-dse
    image: datastax/dse-server:5.1.24
    environment:
      - DS_LICENSE=accept
      - CASSANDRA_YAML=/opt/dse/resources/cassandra/conf
      - DEBEZIUM_HOME=/opt/dse/resources/debezium
    ports:
      - "0.0.0.0:9052:9042"
    links:
      - zookeeper
      - kafka
    volumes:
      - ./configs/:/config/    
      - ./configs/:/home/
      - C:\GitHub\Work\Nitro\workdir\inserts.sql:/home/inserts.sql
  kafka_manager:
    container_name: kafka_manager-dse
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:      
        - "0.0.0.0:9010:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null