version: '3.3'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.6
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2888:2888"
      - "0.0.0.0:3888:3888"
  kafka:
    container_name: kafka
    image: debezium/kafka:1.6
    ports:
      - "0.0.0.0:9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
  cassandra:
    container_name: cassandra
    image: datastax/dse-server:5.1.24
    environment:
      - DS_LICENSE=accept
      - DEBEZIUM_VERSION=1.6.1.Final
      - MAVEN_CENTRAL=https://repo1.maven.org/maven2
      - CASSANDRA_YAML=/opt/dse/resources/cassandra/conf
      - DEBEZIUM_HOME=/opt/dse/resources/debezium
    ports:
      - "0.0.0.0:9042:9042"
    links:
      - zookeeper
      - kafka
    volumes:
      - C:\GitHub\Work\Nitro\workdir\inserts.sql:/home/cassandra/sqls/insert.sql
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\dc_config\:/config/
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\:/home/
  kafka_manager:
    container_name: kafka_manager
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:      
        - "0.0.0.0:9000:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null          