version: '3.3'
services:
  cassandra:
    container_name: cassandra
    image: datastax/dse-server:5.1.24
    environment:
      - DS_LICENSE=accept
      - DEBEZIUM_VERSION=1.6.1.Final
      - MAVEN_CENTRAL=https://repo1.maven.org/maven2
      - CASSANDRA_YAML=/opt/dse/resources/cassandra/conf
      - DEBEZIUM_HOME=/opt/dse/resources/debezium
    ports:
      - "0.0.0.0:9042:9042"
    volumes:
    #   - /var/lib/cassandra
      - C:\GitHub\Work\Nitro\workdir\inserts.sql:/home/cassandra/sqls/insert.sql
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\cassandra.yaml:/config/cassandra.yaml
      # - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\cassandra-dse.yaml:/config/cassandra.yaml
      # - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\cassandra-dse.yaml:/home/cassandra.yaml
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\config.properties:/home/config.properties
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\inventory.cql:/home/inventory.cql
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\log4j.properties:/home/log4j.properties
      - C:\GitHub\Work\Nitro\final\.build\dse-debezium-init\startup-script.sh:/home/startup-script.sh