version: '3.3'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.6
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2888:2888"
      - "0.0.0.0:3888:3888"
  kafka:
    container_name: kafka
    image: debezium/kafka:1.6
    ports:
      - "0.0.0.0:9092:9092"
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
  cassandra:
    container_name: cassandra
    image: anieshaz/cassandra:3.11
    ports:
      - "0.0.0.0:9042:9042"
    links:
      - zookeeper
      - kafka
    volumes:
      - /var/lib/cassandra
      - C:\GitHub\Work\Nitro\workdir\inserts.sql:/home/cassandra/sqls/insert.sql
      - C:\GitHub\Work\Nitro\debezium-connector\example\debezium-cassandra-init\cassandra.yaml:/opt/cassandra/conf/cassandra.yaml
      # - C:\GitHub\Work\Nitro\final\.build\debezium-cassandra-init\config.properties:/debezium/config.properties
    depends_on:
      - schema_registry
  kafka_manager:
    container_name: kafka_manager
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:      
        - "0.0.0.0:9000:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null          
  connect:
    container_name: connect
    image: anieshaz/connect:1.0
    ports:
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:5005:5005"
    links:
      - mysql_target_db
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=connect_configs
      - OFFSET_STORAGE_TOPIC=connect_offsets
      - STATUS_STORAGE_TOPIC=connect_statuses
  connect_ui:
    container_name: connect_ui
    image: landoop/kafka-connect-ui
    ports:
      - "0.0.0.0:8003:8000"
    environment:
      - CONNECT_URL=http://connect:8083
    depends_on:
      - connect
  schema_registry:
    container_name: schema_registry
    image: confluentinc/cp-schema-registry
    ports:
        - "0.0.0.0:8181:8181"
    environment: 
        # - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
        - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:9092
        - SCHEMA_REGISTRY_HOST_NAME=schema-registry
        - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    links:
        - zookeeper
  mysql_target_db:
    container_name: mysql_target_db
    image: mariadb:10.3.24-focal
    environment: 
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=digicert_com
        - MYSQL_USER=debezium
        - MYSQL_PASSWORD=debezium
    volumes:
        - ./db_mnt/target/mysql_data:/var/lib/mysql
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        # - ./mysql/digicert_com_replication.sql:/home/digicert_com_replication.sql
        # - ./mysql/certopedia.sql:/home/certopedia.sql
    ports:
        - "0.0.0.0:33060:3306"        