version: '3.3'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.3
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: debezium/kafka
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  cassandra:
    container_name: cassandra
    image: anieshaz/debezium-cassandra:1.6
    ports:
      - 9042:9042
    links:
      - zookeeper
      - kafka
    volumes:
      - ./db_mnt:/var/lib/cassandra
      - ./build_cassandra/cassandra.yaml:/opt/cassandra/conf/cassandra.yaml 
      - ./build_cassandra/debezium-connector-cassandra.jar:/debezium/debezium-connector-cassandra.jar
      - ./build_cassandra/log4j.properties:/debezium/log4j.properties
      - ./build_cassandra/config.properties:/debezium/config.properties
      - ./build_cassandra/inventory.cql:/debezium/inventory.cql      
      - C:\Work\Nitro\workdir\random_inserts.py:/debezium/random_inserts.py
    # command:  >
    #   bash -c "
    #   chmod 777 /opt/cassandra/conf/cassandra.yaml &&
    #   chmod 777 /debezium/debezium-connector-cassandra.jar &&
    #   chmod 777 /debezium/log4j.properties &&
    #   chmod 777 /debezium/config.properties &&
    #   # java -Dlog4j.debug -Dlog4j.configuration=file:/debezium/log4j.properties -jar /debezium/debezium-connector-cassandra.jar /debezium/config.properties
    #   "
  # connect:
  #   container_name: connect
  #   image: anieshaz/connect:1.0
  #   ports:
  #     - 8083:8083
  #   links:
  #     - kafka
  #     - cassandra
  #   environment:
  #     - BOOTSTRAP_SERVERS=kafka:9092
  #     - GROUP_ID=1
  #     - CONFIG_STORAGE_TOPIC=connect_configs
  #     - OFFSET_STORAGE_TOPIC=connect_offsets
  #     - STATUS_STORAGE_TOPIC=connect_statuses
