version: '3.3'
services:
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:1.6
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka
    image: debezium/kafka:1.6
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181/kafka
  cassandra:
    container_name: cassandra
    image: debezium/example-cassandra:1.6
    build:
      context: ./debezium-cassandra-init
    ports:
      - 9042:9042
    links:
      - zookeeper
      - kafka
    volumes:
      - /var/lib/cassandra
      - C:\GitHub\Work\Nitro\workdir\inserts.sql:/home/cassandra/sqls/insert.sql
      - C:\GitHub\Work\Nitro\debezium-connector\example\debezium-cassandra-init\cassandra.yaml:/opt/cassandra/conf/cassandra.yaml
  kafka_manager:
    image: hlebalbau/kafka-manager:1.3.3.18
    ports:      
        - "0.0.0.0:9000:9000"
    environment:
        ZK_HOSTS: "zookeeper:2181"
        APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null          
  # connect:
  #   container_name: connect
  #   image: debezium/connect:1.6
  #   ports:
  #     - 8083:8083
  #   links:
  #     - kafka
  #     - cassandra
  #   environment:
  #     - BOOTSTRAP_SERVERS=kafka:9092
  #     - GROUP_ID=1
  #     - CONFIG_STORAGE_TOPIC=my_connect_configs
  #     - OFFSET_STORAGE_TOPIC=my_connect_offsets
  #     - STATUS_STORAGE_TOPIC=my_connect_statuses
